### ISSUE TITLE
[BUG] Unchecked runtime.lastError: Could not establish connection on toolbar button click.

### ISSUE THREAD

**Issue by msrouchou** [bengarrett/RetroTxt#153]
**Describe the bug**
I used to be able to use RetroTxt on raw GitLab job logs (ANSI colored), but since recent updates, this won't work for me anymore.

**To Reproduce**
1. Go to ['this random example log'](https://gitlab.com/gitlab-org/gitlab/-/jobs/3588310963/raw)
2. Activate RetroTxt to request the logs be processed
4. wait indefinetly

**RetroTxt**
v5 on Google Chrome 109
Windows with Intel x64

**Additional context**
I had the issue since a logn time now, I can't remember the exact verison that broke it for me, maybe version 5 ?

Thank you :)

**Comment by msrouchou** [comment]
I did not assign `bengarrett`, I guess it is an automatic process :)

**Comment by bengarrett** [comment]
Hi, thank you for reporting this and providing the example!

I believe it only effects version 5. It was rewritten to use the new, controversial Chrome API that Google is eventually forcing all extensions to use. Hopefully I can get this fixed soon.

**Comment by bengarrett** [comment]
Hi @msrouchou, thankfully this is an easy fix.

Google has had a lot of bad press with rogue web extensions on the Chrome web store. The new Chrome extension API seriously clamps down on the ability of extensions to read browser tabs and content.

When you were clicking on the RetroTxt icon, Chrome was blocking RetroTxt from accessing the tab or letting it know it was being blocked.

![Screenshot 2023-01-23 123954](https://user-images.githubusercontent.com/513842/213952867-b9cc8dc7-dad8-421a-a06f-d0d9ff8a4547.png)

For any new website or domain hosting text/ansi files, you have to go to the RetroTxt settings and do the following.

- Paste the URL to the input (marked in yellow) and click add.
- The (marked blue) toggle will automatically disable and you'll have to re-enable it. This manual process is needed by Chrome, to confirm you're not a dubious script or bot.
- The RetroTxt button should now work whenever your reading logs on gitlab's CDN. If in the future, you want to drop access, click the delete X button next to the domain (green arrow).

I will need to see if there is a way to give some feedback when a browser tab is inaccessible when clicking the RetroTxt toolbar button.

![Screenshot 2023-01-23 122557](https://user-images.githubusercontent.com/513842/213952807-05a037ae-4d8b-4ad6-8f1b-00c4efc48f72.png)

![Screenshot 2023-01-23 122247](https://user-images.githubusercontent.com/513842/213952846-6bc5bf9b-a2f9-4a9e-96d0-fbb199f60a9f.png)

**Comment by bengarrett** [comment]
Hi @msrouchou, the good news this is a easy fix.

You have to manually add any new website domain that you wish to use RetroTxt on. Otherwise a web extension could quietly sit in the background and read any browser tab you had opened.

In the RetroTxt Options, click the Settings tab.

You then can paste the URL into the input box and click add to include the cdn.artifacts.gitlab-static.net domain. 

![Screenshot 2023-01-23 131403](https://user-images.githubusercontent.com/513842/213955950-b00948af-6ae6-4fe4-9b8c-99988c1dbfbf.png)

From there, refresh the tab viewing https://cdn.artifacts.gitlab-static.net/a6/80/a68072e80f075e89bc74a300101a9e71e8363bdb542182580162553462480a52/2023_01_11/3588310963/3924850946/job.log and it should display!

![Screenshot 2023-01-23 131828](https://user-images.githubusercontent.com/513842/213956045-d2cf311f-2f26-4ddd-ba30-1fa27b3284b8.png)

---

There is still a bug though so please leave this issue open. Currently when someone clicks the RetroTxt toolbar button, there is no feedback when trying to use RetroTxt on a blocked page. Chrome instead throws a background error that cannot be captured or processed.

![Screenshot 2023-01-23 123954](https://user-images.githubusercontent.com/513842/213956209-dab00f26-1731-44c9-b129-1e0d546c36b2.png)

**Comment by bengarrett** [comment]
Done.
