### ISSUE TITLE
[FEATURE] Add size setting to ... well, settings

### ISSUE THREAD

**Issue by dei-layborer** [bengarrett/RetroTxt#193]
I use RetroTxt more for reading text files than ANSI art, so I hope this isn't going too far down a customization rabbit hole than you'd like.  Also, please note that I use Firefox, so am of course using the manifest v2 version of RetroTxt.

Anyway, I'm using a 4K screen, and I find the default text size a little bit too small (thank you, aging).  I'd like to be able to change the default zoom level (or font size) in settings, rather than having to change it every time a text doc loads.

While I'm asking for all and sundry, would it be possible to have more control over the line width for text files?  For whatever reason, text files render with no margin on either side, meaning lines go as far to both edges as possible.  This hurts readability IMO.

If you're trying to avoid changing the v2 version, would you object to my making a pull request to implement this/these?

**Comment by bengarrett** [comment]
Hi Dei, 

The main reason there is no hard font size adjustment is that it is always something that has been handled via a browser settings. In Firefox it is known as Default Zoom.

<img width="901" alt="Screenshot 2024-05-16 at 16 49 20" src="https://github.com/bengarrett/RetroTxt/assets/513842/382dea56-736c-4491-9da5-c4ee764f845d">

---

For the other request I believe you're after a centred, text container. That's something I could probably add to MV3 but unfortunately, I would not add to Firefox. I'll spare you my opinions on Mozilla's lack of priorities for Firefox 😅

But you're always welcome to create a pull request with `manifest-v2`.

There's a MV2 branch that still works with Firefox: https://github.com/bengarrett/RetroTxt/tree/manifest-v2

And these instructions should allow you to load the source into Firefox:
https://github.com/bengarrett/RetroTxt/blob/manifest-v2/docs/source_code.md#use-on-firefox

There's still 100 or so active users of the Firefox addon, so any changes would need to be toggled in the Options page and set to off by default:
https://github.com/bengarrett/RetroTxt/blob/manifest-v2/ext/html/options.html

Otherwise, if that's too much work, you could always modify a custom unsigned extension build for yourself without the need of a config UI. But this would only work in Firefox Developer Edition, see _Testing unsigned extensions_:
https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/#using-web-ext-section

**Comment by dei-layborer** [comment]
Got it, and thanks for the information!  I'll see what I can come up with.

**Comment by bengarrett** [comment]
Hi, I am going to close this, as the next Chromium release has this implementation. But please feel free to offer a pull request for Firefox.

![Screenshot from 2024-05-25 16-16-16](https://github.com/bengarrett/RetroTxt/assets/513842/be36efcb-398c-4095-86a1-38629b79f0c7)
