### ISSUE TITLE
[BUG]Bad rendering of an ansi file

### ISSUE THREAD

**Issue by BackSpace54** [bengarrett/RetroTxt#232]
**Describe the bug**
RetroTxt seems to have a problem with this ANSI file (see attached file), rendering is broken

**To Reproduce**
- Get readme.ans file
- Drag n Drop it in the browser
- Big letters TNZ are broken
- No problem to render the file in PabloDraw

**Screenshots**
<img width="1160" alt="chrome_3FgYj9goo3" src="https://github.com/user-attachments/assets/bd04cf22-a181-4f00-8216-ada1e0bd601d">

**RetroTxt (access Options and click the about tab)**
- v5.5.0 on Google Chrome 131

**Browser (please complete the following information):**
 - OS: Windows 11
 - Browser: Chromium
 - Version 131.0.6778.112

**Additional context**
Below the ANSI file in zip format as .ans is not allowed in GH
[readme.zip](https://github.com/user-attachments/files/18050019/readme.zip)

**Comment by bengarrett** [comment]
Hi BackSpace54, thanks for the thorough report and the useful attachment.

Thankfully, this is is a configuration issue rather than a bug.

- Go to the RetroTxt **Display** options.
- Under **Text**.
- Enable **Narrow wrap**
- Reload the page with `readme.ans`.

> This option enforces an 80-character text width for all ANSI and BBS texts or a 60em CSS value for plain texts to simulate a traditional terminal screen. Any open tabs will require a reload.

It is off by default as many users of RetroTxt view modern texts or logs embedded with color codes, and locking the display to 80 characters is annoying for them.

![Screenshot From 2024-12-08 11-31-19](https://github.com/user-attachments/assets/311d713b-3297-4146-9e02-0e8cb1a28e9a)

**Comment by BackSpace54** [comment]
Hi Ben,
oh my... sorry for false report.
I close the issue, nice extension btw ;-)
Have a nice day.

**Comment by bengarrett** [comment]
Not a problem at all. I am sure you are not the first person to have experienced such an issue with an older ANSI artwork and thought something must be broken.
