### ISSUE TITLE
RetroTxt is not applied to new background tabs

### ISSUE THREAD

**Issue by Keith94** [bengarrett/RetroTxt#26]
I have RetroTxt set to apply to any local text files, it works for tabs in foreground but not for background tabs... I made a short screencast here: https://a.pomf.cat/qnsmjz.mp4

**Comment by bengarrett** [comment]
Hi Keith, thanks for the feedback.

This is a known issue that I haven't worked out how to fix yet.

> when tab is not active, tab.status "complete" is not returned by Chrome

Chrome has events that give extensions such as RetroTxt notifications when tabs have been created, changed and closed. There seems to be an inconsistency when using `file:///` URLs where Chrome does not tell RetroTxt that a new background tab is _complete_, i.e. finished loading the local file.

**Comment by bengarrett** [comment]
The effected code.

`eventpage.js` Line 601

```JavaScript
        if (url.length === 0) { // do nothing
        } else if (tab.active === false && tab.status === "loading" && url.startsWith(`file:///`) === true) {
          // when tab is not active, tab.status "complete" is not returned by Chrome
          runParseEventUrls(`onCreated`, url, tab.id);
        } else if (tab.status === "complete") {
          runParseEventUrls(`onCreated`, url, tab.id);
        }
```

**Comment by Keith94** [comment]
I see, this is Firefox btw if that makes a difference.

**Comment by bengarrett** [comment]
Unfortunately, I think it's an (intentional?) web extension design flaw regardless of browsers.

I remember working on this issue. The current broken system relies on new tab event. The preferred option was the have it depend on the update tab event.

The problem was the update tab event got triggered multiple times, and there was no way to distinguish between a new tab and refresh (F5) updates. So you had an issue where the tab would render with RetroTxt then straight after revert it back to the original text. Having this happen at the same time on multiple background tabs with large text or ANSI files slowed down the browser considerably.
