### ISSUE TITLE
Attempt to transform file being viewed via file:// causes endless spinner

### ISSUE THREAD

**Issue by dreamlayers** [bengarrett/RetroTxt#39]
If I open a text file via a file:// URL in Chrome 57.0.2987.133 32-bit in Windows 7, and then click on the RetroTxt toolbar button, the tab goes black and there is a big progress spinner. It seems this would go on forever, with nothing actually happening. I can use the mouse to highlight the un-transformed black-on-black text forming the black background and make it visible. This happens with both .nfo and .txt extensions.

I tried starting Chrome with `--allow-file-access-from-files` in case that was necessary and confirmed the option took effect, but this did not change anything.

If instead use  `python -m SimpleHTTPServer` and access the same files via http:// then I can view and transform .txt files, though if I try .nfo then Chrome wants to download it.

**Comment by bengarrett** [comment]
I am away at the moment so I can't test this, but I'll look at it when I get back. Chrome and Firefox impose heavier restrictions for webextensions when viewing a file using the file:// protocol instead of http://.

You may need to unchecked then reselect **Allow access to the file URLs** in the addons settings.

**Comment by dreamlayers** [comment]
Sorry, I didn't notice that. Yes, it works after I enable "Allow access to the file URLs". Feel free to close this. Though it would be nice if when the option wasn't enabled there was some error message directing the user to that option, and not just an endless spinner.

**Comment by bengarrett** [comment]
It seems to be a weird quirk (bug?) in chrome. On a first time install, the file:// permission setting Chrome displays to the user and gives the extension isn't the same as it uses internally. I haven't been able to isolate it to a useful test case for a bug report.

The spinner btw is like a last resort alert to show something failed, basically the extension's version of an uncatchable, fatal error. Otherwise Chrome will just continue use the ext, partially render and silently fail which was very confusing :)
