### ISSUE TITLE
Double separator in context menu

### ISSUE THREAD

**Issue by Keith94** [bengarrett/RetroTxt#50]
Observed on Firefox.

![image](https://user-images.githubusercontent.com/5490615/33902224-3475e088-df29-11e7-9b76-ad97de2a9bd4.png)

**Comment by bengarrett** [comment]
Hi Keith,
Is that FF57?

**Comment by Keith94** [comment]
Nope, it's Nightly 59.0a1 (2017-12-12)

**Comment by bengarrett** [comment]
Oh thanks.
I don't work with nightly builds as they are beta software and can break features that may get fixed in future nightly releases.

Firefox Nightly gets a new version every day and as a consequence, the release notes for the Nightly channel are updated continuously to reflect features that have reached sufficient maturity to benefit from community feedback and bug reports. Features listed here may or may not make a final release of Firefox.

**Comment by Keith94** [comment]
That's fair. So I'm guessing it's not reproducible on FF57? I haven't tested there.

**Comment by bengarrett** [comment]
I can't test atm as I don't have access to a machine that can use FF's Gecko engine. Won't be able to check until after Christmas.

**Comment by bengarrett** [comment]
Fixed, will be included in the next release.
