### ISSUE TITLE
Text garbled with UTF-8 encoding

### ISSUE THREAD

**Issue by Keith94** [bengarrett/RetroTxt#53]
In Firefox I set `intl.charset.fallback.utf8_for_file` to "true" in about:config to workaround [markdown file issues](https://github.com/KeithLRobertson/markdown-viewer/issues/37).

But with UTF-8 as default, ASCII art doesn't render correctly:

`The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.`

Is there anything I can do?

**Comment by bengarrett** [comment]
This is a great example of the problem with individual legacy 8bit code pages and why Unicode was created 😉 As there is metadata to identify the document encoding the viewer doesn't know what to do with it.

In Firefox if you go to the **Alt** context menu > View > Text encoding > Western. That should force the tab to render in Windows 1252.

**Comment by bengarrett** [comment]
Yes only per tab, as with that config you're telling Firefox to use UTF-8 encoding on files:/// ? RetroTxt doesn't make any modifications to UTF-8 files because there should be nothing to change. 
For example ▓ is a UTF-8 character and any app, browser, etc that can view UTF-8 will always display it as shaded block. It's also how emojis work across platforms.

You could create a different user profile with your browser  and swap between the two based on your configurations. Chrome user profiles are more seamless than Firefox.

**Comment by Keith94** [comment]
Alright, thanks for the info!
