### ISSUE TITLE
Vertical lines appearing in art portions

### ISSUE THREAD

**Issue by Keith94** [bengarrett/RetroTxt#59]
**Describe the bug**
Any ASCII art seems to have small vertical lines that are repeated.

**To Reproduce**
1. Open [tinyiso.nfo.zip](https://github.com/bengarrett/RetroTxt/files/2751749/tinyiso.zip)

**Expected behavior**
Look more like infekt, without vertical lines.

**Screenshots**
![infekt-win64_2019-01-11_22-09-09](https://user-images.githubusercontent.com/5490615/51069948-ba631980-15ed-11e9-82cf-2410b0af4496.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome 73

**Comment by bengarrett** [comment]
Hi Keith, this is a known issue and is well out of the control of RetroTxt.

The problem lies with [Windows ClearType](https://docs.microsoft.com/en-us/typography/cleartype/) and how it is handled by the browser. Chrome on Windows applies ClearType font smoothing to all Unicode block and shade characters that introduces these graphic artefacts.

Example: `███████████████████` 
 
There is a hack in RetroTxt that you can use to hide most of the artefacts but it will also blur all other text in the document.

In RetroTxt **Options** > **Text render** and select **Smeared**.
