### ISSUE TITLE
Extension causes a download loop

### ISSUE THREAD

**Issue by tiborsaas** [bengarrett/RetroTxt#66]
When I click on specific download links on any website, RetroTxt somehow causes the download to break and stuck in an infinite loop of opening / closing the downloaded file flooding my download history.

The only way to stop the download loop is to quit chrome. 

I turned off all my extensions and traced it back to this one.

for example: https://html5up.net/

![image](https://user-images.githubusercontent.com/342688/55228339-27b03f00-521a-11e9-95ff-1df28ceb695d.png)

**Comment by bengarrett** [comment]
Hi, thanks for the report and sorry for the late response. 

[This issue was reported in the previous version of RetroTxt](https://github.com/bengarrett/RetroTxt/issues/56) and has been fixed. Can you check the version of RetroTxt you are running to confirm it is the latest, **3.2**?

You can find the version info at `chrome://extensions/` and clicking the extension _Details_ button or in the RetroTxt Options under the _About_ tab.
