### ISSUE TITLE
Header Doesn't Correctly Hide Due To Incorrect Invert Value

### ISSUE THREAD

**Issue by faultywarrior** [bengarrett/RetroTxt#77]
When the header is set to be hidden, it incorrectly stays visible, causing it to be overlaid with the text you're trying to read.  Setting the invert value to 0% when hidden makes this go away.  See attached screenshots of the HTML & resulting changes.

FireFox 71 on MacOS Catalina, Dark Theme in both FireFox and MacOS.  RetroTxt theme set to "green on black fg".

Original HTML:
![Original HTML](https://user-images.githubusercontent.com/25770089/71538462-0daea480-28f1-11ea-98a1-e5617a8a8b17.PNG)

Arrow with original HTML:
![Arrow With Original HTML](https://user-images.githubusercontent.com/25770089/71538461-0d160e00-28f1-11ea-938b-2aaca3f3d0e9.PNG)

Fixed HTML:
![New HTML](https://user-images.githubusercontent.com/25770089/71538468-2919af80-28f1-11ea-83f3-8fba71fceb93.PNG)

Arrow now gone with fixed HTML:
![Arrow With Fixed HTML](https://user-images.githubusercontent.com/25770089/71538460-0d160e00-28f1-11ea-8bb2-0b511e3f4d2e.PNG)

**Comment by bengarrett** [comment]
Hi, thanks for the thorough report. 

By design, the arrow is kept on screen as it functions as a user interface button. Clicking it will reveal or hide the header text. The header checkbox in the option toggles its initial state when a page is loaded rather than to completely remove it from the page.
